export const theme = {
  colors: {
    hoverBgBtn: '#FBE0DC',
    hoverTextBtn: '#FF868E',
    mainBgBtn: '#FFFFFF',
    mainTextBtn: '#FF868E',
    activeBgBtn: '#FF868E',
    activeTextBtn: '#FFFFFF',
    mainBg: '#F8F8F7',
    secondBg: '#FBE0DC',
    boldText: '#1D1D1D',
    regularText: '#8C8C8C',
    greenBg: '#97EAB9',
    pinkBg: '#FF868E',
    yellowBg: '#FFD280',
    mutedGreen: '#97EAB94D',
    mutedPink: '#FF868E4D',
    mutedYellow: '#FFD2804D',
    modal: '#FFFFFF',
    modalSvg: '#F8F8F7',
    homeRect: ' #FBE0DC',
  },
  space: [0, 2, 4, 8, 16, 32, 64, 128, 256],
  fontSizes: {
    xs: '12px',
    s: '16px',
    m: '20px',
    l: '36px',
    xl: '44px',
  },
  fontWeights: {
    normal: 400,
    bold: 500,
  },
  borders: {
    none: 'none',
    normal: '1px solid',
  },
  radii: {
    none: '0',
    normal: '10px',
    round: '20px',
  },
};
